spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3333/personalFinance
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  sql:
    init:
      mode: never
      continue-on-error: false

jwt:
  secret: ${JWT_SECRET}
